version: "0.2"
language: en
files:
  - .github/**/*.{md,txt,yaml,yml}
  - .git/COMMIT_EDITMSG
  - "*.{md,txt,yaml,yml}"
  - dictionaries/**/*.{md,txt,yaml,yml,js,tex}
  - docs/**/*.md
  - LICENSE
words:
  - EDITMSG
  - isentinel
  - jiti
  - pncat
  - unrs
  - lsp
flagWords: []
maxNumberOfProblems: 1000
ignorePaths:
  - .gitignore
  - .vscode/**
  - "*-lock.yaml"
  - "*.aff"
  - "*.dic"
  - "*.gz"
  - "*.lock"
  - "*.log"
  - "*.snap"
  - "*.trie"
  - "**/.git/!(COMMIT_EDITMSG)"
  - "**/.git/!(COMMIT_EDITMSG)/**"
  - CHANGELOG.md
  - cSpell.json
  - cspell.json
  - dictionaries/*/dict/**/*.txt
  - dictionaries/*/src/**
  - .changeset
  - node_modules
  - /package.json
  - snapshots/**
import: []
useGitignore: true
dictionaries:
  - software-terms
  - roblox
  - wally
  - rbxts
dictionaryDefinitions:
  - name: roblox
    path: ./dictionaries/roblox/dict/roblox.txt
  - name: wally
    path: ./dictionaries/wally/dict/wally.txt
  - name: rbxts
    path: ./dictionaries/rbxts/dict/rbxts.txt
overrides:
  - filename: "**/package.json"
    ignoreRegExpList:
      - devDependencies
    patterns:
      - name: devDependencies
        description: Ignore "devDependencies"
        pattern: |
          /"devDependencies": \{[^}]*?\}/g
cache:
  cacheStrategy: content
  useCache: true
enableFiletypes:
  - shellscript
