# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: rbxts
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/rbxts.txt
    generateNonStrict: false
    sort: true
keepRawCase: false
checksumFile: true
